"""Training Center content: knowledge base articles, FAQs, quizzes, resources.
Quiz answers live server-side only — the public content endpoint strips them."""

ARTICLES = [
    {
        "slug": "first-week-checklist", "title": "Your first week in SaloneHCM", "role": "Everyone", "minutes": 4,
        "body": [
            "## Day one: sign in and look around",
            "Use the work email and password your administrator gave you. If your organisation enforces two-factor authentication you will also enter a 6-digit code from an authenticator app. After signing in, open the Feature Directory (second item in the sidebar) — it lists every module with a plain-language description and tells you which ones your role and plan unlock.",
            "## Day two: your own records",
            "Open Self-Service and confirm your personal details, bank account and NASSIT number are correct. Errors here become payroll errors later. Download your latest payslip PDF so you know where to find it.",
            "## Day three to five: your role's module",
            "Watch the training video for your role (Administrator, HR Officer, Payroll Officer, or Employee Self-Service) on the Videos page, then take the matching quiz in the Training Center. A pass of 70% or better earns a downloadable certificate.",
            "## If you get stuck",
            "Every page has descriptive empty states, and the Training Center FAQ answers the questions new users ask most. Your administrator can fix access problems in Users & Access in under a minute.",
        ],
    },
    {
        "slug": "understanding-sl-payroll", "title": "How Sierra Leone payroll is calculated", "role": "Payroll officers", "minutes": 6,
        "body": [
            "## Gross to net, step by step",
            "SaloneHCM computes each employee in this order: basic salary plus allowances gives gross pay; NASSIT employee contribution (5% of gross) is deducted; NRA PAYE is applied on the progressive monthly bands; loan repayments and other deductions come off last. What remains is net pay.",
            "## The PAYE bands",
            "PAYE uses the NRA progressive monthly bands configured for your tenant. The first band is tax-free; each band above it is taxed at its marginal rate. Because the calculation is band-by-band, a raise never reduces take-home pay.",
            "## NASSIT",
            "Employees contribute 5% and employers 10% of gross. Both figures appear on the payslip and in the NASSIT schedule export on the Compliance page.",
            "## Why preview matters",
            "The Preview button computes the entire run without committing anything. Check headcount, gross totals and net totals against last month before you press Run. For government tenants, the run is additionally guarded by the budget check, the payroll cut-off lock and the MoF approval chain.",
        ],
    },
    {
        "slug": "voucher-workflow-explained", "title": "The payroll voucher workflow, explained", "role": "Finance & branch staff", "minutes": 5,
        "body": [
            "## One repository, one truth",
            "Every branch, district office or ministry submits its monthly payroll voucher into the central repository — no spreadsheets by email, no paper folders. The Finance Department sees every voucher's stage in real time, and missing branches are listed on the summary cards.",
            "## The stages",
            "Draft → Awaiting supervisor → Submitted → Under review → Approved → Payment authorized. A voucher may be Returned for correction from any pre-payment stage; the reviewer must write a reason of at least 10 characters, the branch corrects and resubmits, and the revision number increments.",
            "## Who does what",
            "Branch officers or supervisors create and submit vouchers. The branch supervisor approves before the voucher reaches headquarters. A finance officer reviews and approves — but never a voucher they created themselves. Finally an MoF approver or admin authorizes payment, and that person must differ from both the creator and the finance approver.",
            "## The rails you cannot break",
            "One voucher per branch per period. No employee on two active vouchers in the same month. No edits after submission unless officially returned. No deletion after submission. Payment-authorized vouchers are permanent immutable records. Every transition is written to the voucher's timeline and the audit log.",
        ],
    },
    {
        "slug": "roles-and-permissions", "title": "Roles, flags and separation of duties", "role": "Administrators", "minutes": 4,
        "body": [
            "## Three roles",
            "Superadmin manages the platform and all tenants. Admin manages one organisation: employees, payroll, settings, users. Employee sees self-service plus anything their flags unlock.",
            "## Two capability flags",
            "Finance Officer lets a user (even employee-role) review and approve payroll vouchers across all branches. MoF Approver lets a user sign payroll runs and authorize voucher payments. Both are toggled per user on the Users & Access page.",
            "## Branch supervisors",
            "A supervisor is set on each branch (Vouchers → Branches & Offices). Supervisors approve their branch's vouchers before submission to headquarters and can create vouchers for their branch.",
            "## Separation of duties is enforced by software",
            "The creator of a voucher cannot finance-approve it. The payment authorizer must differ from both the creator and the approver. Multi-signature MoF approval can require up to 5 distinct signatures per payroll run. Plan your staffing so at least three people hold financial powers.",
        ],
    },
    {
        "slug": "leave-and-attendance-basics", "title": "Leave & attendance: the daily rhythm", "role": "HR officers & employees", "minutes": 4,
        "body": [
            "## Requesting leave",
            "Employees request from the Leave page: pick dates, choose the leave type, submit. Balances are checked automatically and the manager is notified. Status moves from pending to approved or rejected, visible to the employee at all times.",
            "## Approving leave",
            "HR and managers see requests with balance context and overlapping team absences. Approve or reject with a comment; the decision is logged.",
            "## Attendance",
            "Employees clock in and out on the Attendance page. HR can correct records when devices fail — every correction is audit logged. Timesheet totals feed payroll, so month-end corrections should happen before the payroll run.",
        ],
    },
    {
        "slug": "budget-checks-explained", "title": "Pre-payroll budget checks (Gov tier)", "role": "Government payroll teams", "minutes": 5,
        "body": [
            "## Why they exist",
            "A payroll run that overspends a budget line is a finding waiting to happen. The budget check verifies — before the run commits — that every budget code the run will consume has allocation remaining for the period.",
            "## How it works",
            "On the Payroll page, the budget balances panel shows each code's allocation, consumption and remaining balance. When you run payroll, the latest budget check for the period must be green. If any code would go over, the run is blocked with the exact codes listed.",
            "## Overrides",
            "A blocked check can be overridden only by an authorised officer with a written justification. The override, the reason and the officer are permanently recorded and appear in variance reports.",
            "## Cut-off locks",
            "After the monthly cut-off, payroll changes are locked to prevent last-minute insertions. Late corrections flow through retro-pay in the next period instead — visible, calculated, and audited.",
        ],
    },
    {
        "slug": "transparency-portal", "title": "The Open-Gov transparency portal", "role": "Government communications", "minutes": 3,
        "body": [
            "## Public by design",
            "Gov-tier tenants can publish a public transparency page — no login — showing aggregate payroll statistics: headcount, wage bill trend, grade distribution and ministry breakdowns. Personal data never appears.",
            "## Managing it",
            "Enable or disable the portal in Settings. The page updates automatically from approved payroll runs, so published numbers always match the books.",
            "## Why it matters",
            "Journalists and citizens get real numbers from the source, and your ministry gets ahead of misinformation with zero extra reporting work.",
        ],
    },
    {
        "slug": "troubleshooting-access", "title": "Troubleshooting: 'I can't see a feature'", "role": "Everyone", "minutes": 3,
        "body": [
            "## Check the Feature Directory first",
            "Open Feature Directory from the sidebar. Every module shows one of three statuses: Available (click to open), Requires a higher plan (your organisation's tier doesn't include it), or Admin/Superadmin only (your role doesn't include it).",
            "## Common causes",
            "Locked by tier: ask your administrator about upgrading in Settings → Plan. Locked by role: an admin can grant flags (Finance Officer, MoF Approver) in Users & Access. Wrong URL: previews and older links expire — always use your organisation's official app address.",
            "## Still stuck?",
            "Your administrator can check the audit log for failed actions, and the Training Center FAQ covers login, password resets and two-factor issues.",
        ],
    },
]

FAQS = [
    {"q": "I forgot my password. What do I do?",
     "a": "Ask your administrator — they can set a new password for you in Users & Access in under a minute. You'll sign in with the new password immediately."},
    {"q": "Why don't I see the same menu items as my colleague?",
     "a": "The sidebar only shows what your role and your organisation's plan unlock. Open the Feature Directory to see every module and exactly why one is locked for you."},
    {"q": "How do I download my payslip?",
     "a": "Go to Self-Service, find the month you need, and click the payslip to download the PDF. Every payslip since you joined stays available."},
    {"q": "Payroll is blocked with 'budget check' — what now?",
     "a": "The period's budget check found a code that would go over its allocation. Review the budget balances panel on the Payroll page, adjust the allocation with Finance, or record a documented override if authorised."},
    {"q": "Why can't I approve the voucher I just submitted?",
     "a": "Separation of duties: the person who creates a voucher can never finance-approve it, and the payment authorizer must differ from both the creator and the approver. Ask another finance officer to review it."},
    {"q": "A voucher has a mistake but it's already submitted. Can I edit it?",
     "a": "No — submitted vouchers are immutable. A reviewer must Return it for correction with a written reason. It then becomes editable, and resubmitting increments the revision number so the correction history is permanent."},
    {"q": "Can two branches submit vouchers for the same employee?",
     "a": "No. The double-pay guard rejects any voucher that lists an employee who already appears on another active voucher for the same period."},
    {"q": "How do I give someone payroll approval powers?",
     "a": "On Users & Access, use the banknote toggle to grant the Finance Officer flag (voucher review/approval) — MoF Approver (run signing and payment authorization) is granted the same way. Both are audit logged."},
    {"q": "What is the multi-signature MoF approval?",
     "a": "Gov tenants can require up to 5 distinct MoF signatures before a payroll run is approved. A superadmin dials the threshold on the Payroll page."},
    {"q": "How is PAYE calculated?",
     "a": "On the NRA progressive monthly bands: the first band is tax-free and each band above is taxed at its marginal rate. The payslip shows the exact figure per employee."},
    {"q": "Does the employer pay NASSIT too?",
     "a": "Yes — employees contribute 5% of gross and employers 10%. Both appear in the NASSIT schedule export on the Compliance page."},
    {"q": "Are the training quizzes graded? Do I get a certificate?",
     "a": "Yes. Each quiz has a 70% pass mark. Pass and you can download a personalised certificate PDF with a verification code."},
    {"q": "Who can see the transparency portal?",
     "a": "Anyone — it's a public page with aggregate statistics only. Personal data never appears on it."},
    {"q": "My preview link stopped working. Which address should I use?",
     "a": "Preview links are temporary. Use your organisation's official deployed address for daily work — ask your administrator for it."},
]

QUIZZES = [
    {
        "id": "onboarding", "title": "Getting Started certification", "role": "Everyone", "pass_pct": 70,
        "questions": [
            {"q": "Where can you see every module in SaloneHCM with its availability status?",
             "options": ["The dashboard", "The Feature Directory", "The audit log", "The billing page"], "answer": 1},
            {"q": "What does the sidebar show you?",
             "options": ["Every feature that exists", "Only modules your role and plan unlock", "Only admin tools", "A fixed list for all users"], "answer": 1},
            {"q": "Your organisation enforces 2FA. What do you need besides your password?",
             "options": ["A hardware key", "An SMS from your bank", "A 6-digit code from an authenticator app", "Nothing else"], "answer": 2},
            {"q": "Where do you check and download your own payslips?",
             "options": ["Compliance", "Self-Service", "Users & Access", "Documents"], "answer": 1},
            {"q": "A feature card in the Directory says 'Requires Salone HCM Enterprise'. What does that mean?",
             "options": ["Your account is broken", "Your role is too junior", "Your organisation's plan doesn't include it", "The feature was removed"], "answer": 2},
            {"q": "Who fixes a forgotten password?",
             "options": ["Only Emergent support", "Your administrator, in Users & Access", "Nobody — make a new account", "The payroll officer"], "answer": 1},
        ],
    },
    {
        "id": "administrator", "title": "Administrator certification", "role": "Administrators", "pass_pct": 70,
        "questions": [
            {"q": "Which flag lets a user review and approve payroll vouchers?",
             "options": ["MoF Approver", "Finance Officer", "Branch Supervisor", "Superadmin"], "answer": 1},
            {"q": "What does the MoF Approver flag additionally allow?",
             "options": ["Editing salaries", "Signing payroll runs and authorizing voucher payments", "Deleting audit logs", "Creating tenants"], "answer": 1},
            {"q": "Where do you define branches and their supervisors?",
             "options": ["Settings", "Payroll Vouchers → Branches & Offices", "Employees", "Compliance"], "answer": 1},
            {"q": "Every sensitive action in SaloneHCM is recorded in…",
             "options": ["An email digest", "The audit log", "A paper register", "The dashboard"], "answer": 1},
            {"q": "How many distinct MoF signatures can a payroll run be configured to require?",
             "options": ["Exactly 2", "1 to 5", "Unlimited", "None"], "answer": 1},
            {"q": "Best practice for financial powers is to…",
             "options": ["Give one trusted person everything", "Spread creator, approver and authorizer across at least three people", "Rotate passwords weekly", "Disable the flags"], "answer": 1},
        ],
    },
    {
        "id": "hr-officer", "title": "HR Officer certification", "role": "HR officers", "pass_pct": 70,
        "questions": [
            {"q": "The single source of truth for a person's grade, salary and bank details is…",
             "options": ["The payroll run", "The employee register", "The document vault", "The audit log"], "answer": 1},
            {"q": "When should attendance corrections be completed?",
             "options": ["Any time", "Before the monthly payroll run", "After payday", "Only at year-end"], "answer": 1},
            {"q": "What happens when HR corrects an attendance record?",
             "options": ["Nothing is recorded", "The correction is audit logged", "The employee is suspended", "Payroll is blocked"], "answer": 1},
            {"q": "Leave approvals should consider…",
             "options": ["Only seniority", "Balances and overlapping team absences", "The weather", "Payroll totals"], "answer": 1},
            {"q": "Contracts and identity documents belong in…",
             "options": ["Email attachments", "The secure document vault", "A shared drive", "The transparency portal"], "answer": 1},
            {"q": "Why does clean employee data matter?",
             "options": ["It looks professional", "Payroll, compliance and audits all depend on it", "It reduces server costs", "It is required for 2FA"], "answer": 1},
        ],
    },
    {
        "id": "payroll-officer", "title": "Payroll Officer certification", "role": "Payroll officers", "pass_pct": 70,
        "questions": [
            {"q": "What should you ALWAYS do before committing a payroll run?",
             "options": ["Send the bank file", "Preview the run", "Delete last month's run", "Disable budget checks"], "answer": 1},
            {"q": "In the gross-to-net order, what is deducted at 5% of gross?",
             "options": ["PAYE", "NASSIT employee contribution", "Loan repayment", "Union dues"], "answer": 1},
            {"q": "PAYE is calculated…",
             "options": ["Flat 15% on everything", "Band by band on the NRA progressive monthly bands", "Only on allowances", "Manually by the officer"], "answer": 1},
            {"q": "A gov-tier run is blocked at commit. The most likely guardrail is…",
             "options": ["A missing poster image", "The pre-payroll budget check", "Too many employees", "An expired password"], "answer": 1},
            {"q": "Which bank-file formats can SaloneHCM generate?",
             "options": ["SWIFT only", "Rokel, SLCB, UBA and Ecobank", "Cash envelopes", "None"], "answer": 1},
            {"q": "Statutory monthly obligations tracked on the Compliance page are…",
             "options": ["VAT and customs", "NRA PAYE returns and NASSIT schedules", "Business registration", "Property tax"], "answer": 1},
        ],
    },
    {
        "id": "vouchers", "title": "Payroll Vouchers certification", "role": "Finance & branch staff", "pass_pct": 70,
        "questions": [
            {"q": "How many vouchers may a branch submit per period?",
             "options": ["As many as needed", "Exactly one", "One per employee", "Two"], "answer": 1},
            {"q": "A submitted voucher has a wrong amount. The correct path is…",
             "options": ["Edit it quietly", "Delete and recreate it", "Return it for correction with a written reason", "Ignore it"], "answer": 2},
            {"q": "Who can NEVER finance-approve a voucher?",
             "options": ["The branch supervisor", "The person who created it", "An admin", "A finance officer"], "answer": 1},
            {"q": "The payment authorizer must be different from…",
             "options": ["Nobody", "The creator only", "Both the creator and the finance approver", "The employee on the voucher"], "answer": 2},
            {"q": "An employee already appears on another active voucher this period. Adding them again…",
             "options": ["Is allowed with a note", "Is rejected by the double-pay guard", "Doubles their salary", "Requires 2FA"], "answer": 1},
            {"q": "After payment is authorized, the voucher…",
             "options": ["Can be edited by admins", "Becomes a permanent immutable record", "Is deleted after 30 days", "Returns to draft"], "answer": 1},
        ],
    },
    {
        "id": "gov-modules", "title": "Government Modules certification", "role": "Government payroll teams", "pass_pct": 70,
        "questions": [
            {"q": "Civil-service salaries flow from…",
             "options": ["Ad-hoc numbers per person", "The grade & step salary structure", "The bank statement", "The transparency portal"], "answer": 1},
            {"q": "Establishment control compares…",
             "options": ["Salaries to inflation", "Approved posts against filled posts", "Leave against attendance", "PAYE to NASSIT"], "answer": 1},
            {"q": "A budget check override requires…",
             "options": ["Nothing", "A written justification by an authorised officer, permanently recorded", "A phone call", "Deleting the check"], "answer": 1},
            {"q": "Changes after the monthly payroll cut-off are handled via…",
             "options": ["Editing the closed run", "Retro-pay in the next period", "Cash adjustments", "Ignoring them"], "answer": 1},
            {"q": "The transparency portal shows…",
             "options": ["Individual salaries", "Aggregate statistics only, no personal data", "Bank account numbers", "Voucher line items"], "answer": 1},
            {"q": "Ghost-worker detection flags…",
             "options": ["Employees on leave", "Duplicate NASSIT numbers, shared bank accounts and dormant payslips", "New hires", "Low performers"], "answer": 1},
        ],
    },
]

RESOURCES = [
    {"file": "qrc-getting-started.pdf", "title": "Quick Reference — Getting Started", "kind": "Reference card", "desc": "Sign-in, navigation and the Feature Directory on one page."},
    {"file": "qrc-administrator.pdf", "title": "Quick Reference — Administrator", "kind": "Reference card", "desc": "Users, flags, settings, branches and the audit log."},
    {"file": "qrc-hr-officer.pdf", "title": "Quick Reference — HR Officer", "kind": "Reference card", "desc": "Employees, leave, attendance and documents."},
    {"file": "qrc-payroll-officer.pdf", "title": "Quick Reference — Payroll Officer", "kind": "Reference card", "desc": "Preview → run → payslips → bank files → filing."},
    {"file": "qrc-vouchers.pdf", "title": "Quick Reference — Payroll Vouchers", "kind": "Reference card", "desc": "The workflow stages and every anti-fraud rail."},
    {"file": "qrc-employee.pdf", "title": "Quick Reference — Employee Self-Service", "kind": "Reference card", "desc": "Payslips, leave and attendance for every employee."},
    {"file": "onboarding-checklist.pdf", "title": "Customer Onboarding Checklist", "kind": "Checklist", "desc": "The 4-week rollout plan from kickoff to first live payroll."},
    {"file": "voiceover-scripts.pdf", "title": "Training Video Voiceover Scripts", "kind": "Scripts", "desc": "Full narration text of all 7 training videos."},
    {"file": "deck-administrator.pptx", "title": "Slides — Administrator Essentials", "kind": "Presentation", "desc": "PowerPoint deck for classroom admin training."},
    {"file": "deck-payroll-vouchers.pptx", "title": "Slides — Payroll & Vouchers", "kind": "Presentation", "desc": "PowerPoint deck for payroll and finance teams."},
    {"file": "deck-employee.pptx", "title": "Slides — Employee Self-Service", "kind": "Presentation", "desc": "PowerPoint deck for all-staff onboarding sessions."},
]
