"""Screenplays for the 7 role-specific SaloneHCM training videos."""

ADMIN = ("admin@gov.sl", "GovAdmin@2026")
EMP = ("joseph.williams@gov.sl", "Employee@2026")

VIDEOS = [
    # ------------------------------------------------------------------
    {
        "slug": "getting-started",
        "title": "Getting Started & Onboarding — your first day in SaloneHCM",
        "summary": "Sign in, learn the dashboard, master the navigation, and discover every module with the Feature Directory. The essential first video for every new user.",
        "persona": "general", "sort": 10,
        "scenes": [
            {"chapter": "Welcome",
             "narration": "Welcome to SaloneHCM — Sierra Leone's human capital management and payroll platform. In this getting-started session, we'll sign in for the first time, take a tour of the dashboard, learn the navigation, and show you how to discover every feature available to you. Let's begin.",
             "steps": [("slide", "Module 1 · Getting Started", "Getting Started & Onboarding", "Sign in, dashboard tour, navigation, and the Feature Directory — everything you need for day one.")]},
            {"chapter": "Signing in",
             "narration": "This is the sign-in page. Enter the work email and password provided by your administrator. If your organisation has enabled two-factor authentication, you'll also be asked for a six digit code from your authenticator app. Now watch as we sign in as a system administrator.",
             "steps": [("login", *ADMIN)]},
            {"chapter": "Dashboard tour",
             "narration": "And here is your dashboard — the heart of SaloneHCM. Across the top you'll find live key performance indicators: total headcount, monthly payroll cost, pending leave requests, and compliance status. Everything updates in real time as your team works.",
             "steps": [("goto", "/dashboard"), ("scroll", 350), ("pause", 1.0), ("scroll", -200)]},
            {"chapter": "Navigation",
             "narration": "On the left is your navigation sidebar. It only shows the modules your role and your organisation's plan unlock — so what you see is always what you can use. Core H R sits at the top, followed by payroll and finance, then administration tools.",
             "steps": [("hover", 'a[href="/employees"]'), ("pause", 0.8), ("hover", 'a[href="/payroll"]'), ("pause", 0.8), ("hover", 'a[href="/users"]')]},
            {"chapter": "Feature Directory",
             "narration": "Not sure where something lives? Open the Feature Directory. Every module in the platform is listed here, grouped by function, with a plain-language description and a live status — available, requiring a higher plan, or restricted to administrators. Click any available card to jump straight in.",
             "steps": [("click", 'a[href="/directory"]'), ("pause", 1.2), ("scroll", 500), ("pause", 0.8), ("scroll", 500)]},
            {"chapter": "Your profile & help",
             "narration": "Finally, remember two things: your settings page controls your password and two-factor security, and the Training Center — where you found this video — holds quick reference cards, knowledge base articles, and certification quizzes for every role. You're ready to explore.",
             "steps": [("slide", "You're all set", "Next: take the Onboarding quiz", "Visit the Training Center for reference cards, articles, and your certification test.")]},
        ],
    },
    # ------------------------------------------------------------------
    {
        "slug": "administrator-guide",
        "title": "Administrator Guide — users, access, settings & branches",
        "summary": "For system administrators: inviting users, granting Finance and MoF approval powers, organisation settings, plan tiers, and managing branches and offices.",
        "persona": "government", "sort": 20,
        "scenes": [
            {"chapter": "Welcome",
             "narration": "Welcome to the SaloneHCM administrator guide. As an administrator you control who can access the system, what they're allowed to do, and how your organisation is configured. In the next few minutes we'll cover user management, role flags, organisation settings, branch offices, and the audit log.",
             "steps": [("slide", "Module 2 · Administrators", "Administrator Guide", "Users & access · role flags · organisation settings · branches & offices · audit trail")]},
            {"chapter": "Users & access",
             "narration": "Let's start with users and access. From here you invite new users by email, reset passwords, and remove accounts that are no longer needed. Notice the role pills next to each name — admin, employee, and special capability flags.",
             "steps": [("login", *ADMIN), ("goto", "/users"), ("hover", '[data-testid="users-invite-open"]'), ("pause", 0.8), ("scroll", 300)]},
            {"chapter": "Finance & MoF flags",
             "narration": "Two flags matter greatly for financial control. The Finance Officer flag lets a user review and approve payroll vouchers. The M o F approver flag lets them sign payroll runs and authorise voucher payments. Grant them with one click on the banknote icon — and remember: separation of duties is enforced automatically, so no single person can push money out alone.",
             "steps": [("scroll", -200), ("hover", '[data-testid^="user-finance-toggle-"]'), ("pause", 1.2)]},
            {"chapter": "Organisation settings",
             "narration": "Under settings you manage your organisation profile, your subscription tier, integrations like S M S and email, security policies including two-factor authentication, and the public transparency portal for government tenants.",
             "steps": [("goto", "/settings"), ("scroll", 450), ("pause", 1.0), ("scroll", 450)]},
            {"chapter": "Branches & offices",
             "narration": "If your organisation submits payroll vouchers from multiple branches, districts, or ministries, you define those offices here. Each branch gets a unique code, an optional ministry link, and a branch supervisor whose approval is required before that branch's voucher reaches headquarters. You can also assign employees to their branch from this screen.",
             "steps": [("goto", "/vouchers"), ("click", '[data-testid="vouchers-tab-branches"]'), ("pause", 1.0), ("scroll", 250)]},
            {"chapter": "Audit log",
             "narration": "Finally, the audit log. Every sensitive action in SaloneHCM — every approval, every change, every payment authorisation — is recorded here with who did it and when. If a regulator or the Auditor General asks, the answer is one search away.",
             "steps": [("goto", "/audit"), ("scroll", 350)]},
            {"chapter": "Wrap-up",
             "narration": "That's the administrator essentials: control access tightly, grant financial powers deliberately, keep your settings current, and let the audit log do the remembering. Take the administrator certification quiz in the Training Center to confirm your knowledge.",
             "steps": [("slide", "Administrator Guide complete", "Take the Administrator quiz", "Prove your knowledge and download your certificate from the Training Center.")]},
        ],
    },
    # ------------------------------------------------------------------
    {
        "slug": "hr-officer-training",
        "title": "HR Officer Training — employees, leave, attendance & documents",
        "summary": "The complete human resources workflow: maintaining employee records, approving leave, monitoring attendance, and managing the secure document vault.",
        "persona": "general", "sort": 30,
        "scenes": [
            {"chapter": "Welcome",
             "narration": "Welcome to H R officer training for SaloneHCM. Your work keeps every record accurate — and accurate records are what make payroll, compliance, and audits painless. We'll cover the employee register, leave management, attendance, and the document vault.",
             "steps": [("slide", "Module 3 · HR Officers", "HR Officer Training", "Employee records · leave approvals · attendance · secure document vault")]},
            {"chapter": "Employee register",
             "narration": "The employee register is your single source of truth. Every person's grade, salary, bank details, NASSIT number, and department lives here. Use the search bar to find anyone instantly, and the add employee button to onboard a new hire — the form guides you through every required field, including statutory identifiers.",
             "steps": [("login", *ADMIN), ("goto", "/employees"), ("hover", '[data-testid="add-employee-button"]'), ("pause", 0.7), ("type", '[data-testid="employees-search-input"]', "adama"), ("pause", 1.2)]},
            {"chapter": "Leave management",
             "narration": "Next, leave. Employees request leave from their self-service portal, and those requests arrive here for your approval. You can see balances, overlapping dates, and the team calendar before you decide — so cover gaps never surprise you.",
             "steps": [("goto", "/leave"), ("scroll", 300), ("pause", 1.0)]},
            {"chapter": "Attendance",
             "narration": "Attendance gives you the daily picture: who clocked in, who's absent, and the timesheet totals feeding into payroll. Records can be corrected by H R when a device fails — and every correction is audit logged.",
             "steps": [("goto", "/attendance"), ("scroll", 300)]},
            {"chapter": "Document vault",
             "narration": "Finally, the document vault. Contracts, identity documents, disciplinary letters — uploaded once, stored securely in the cloud, and scoped to your organisation. Use the search and category filters to retrieve anything in seconds.",
             "steps": [("goto", "/documents"), ("hover", '[data-testid="documents-upload-open"]'), ("pause", 0.8), ("scroll", 250)]},
            {"chapter": "Wrap-up",
             "narration": "Remember: clean employee data today prevents payroll disputes tomorrow. When you're ready, take the H R officer quiz in the Training Center and earn your certificate.",
             "steps": [("slide", "HR Officer Training complete", "Take the HR Officer quiz", "Keep records clean — payroll and compliance depend on you.")]},
        ],
    },
    # ------------------------------------------------------------------
    {
        "slug": "payroll-officer-training",
        "title": "Payroll Officer Training — runs, payslips, bank files & compliance",
        "summary": "Run gross-to-net payroll with Sierra Leone PAYE and NASSIT, preview before you commit, export payslips and bank files, and file NRA returns on time.",
        "persona": "general", "sort": 40,
        "scenes": [
            {"chapter": "Welcome",
             "narration": "Welcome to payroll officer training. This is where salaries become payments — correctly, on time, and fully compliant with Sierra Leone's tax law. We'll run a payroll preview, understand the gross-to-net calculation, export payslips and bank files, and look at statutory compliance.",
             "steps": [("slide", "Module 4 · Payroll Officers", "Payroll Officer Training", "Payroll runs · PAYE & NASSIT · payslips · bank files · NRA compliance")]},
            {"chapter": "The payroll engine",
             "narration": "This is the payroll page. Choose the month and year, then always preview before you run. The preview computes every employee's gross pay, applies the N R A progressive P A Y E bands, deducts the five percent NASSIT employee contribution, applies any loan repayments — and shows you the exact net pay, with nothing committed yet.",
             "steps": [("login", *ADMIN), ("goto", "/payroll"), ("hover", '[data-testid="payroll-month"]'), ("pause", 0.6), ("click", '[data-testid="payroll-preview-button"]'), ("pause", 2.0), ("scroll", 400)]},
            {"chapter": "Committing a run",
             "narration": "When the preview looks right, the run button commits it. For government tenants, SaloneHCM first verifies the budget check for the period, respects the payroll cut-off lock, and routes the run into the Ministry of Finance approval chain — where the required number of distinct signatures must be collected before the run is approved.",
             "steps": [("scroll", -300), ("hover", '[data-testid="payroll-run-button"]'), ("pause", 1.4)]},
            {"chapter": "Payslips & bank files",
             "narration": "Every completed run appears in the history below. From there you download individual payslip P D Fs, send bulk payslip S M S messages, and generate bank disbursement files in Rokel, S L C B, U B A, or Ecobank format — ready for upload to your bank portal.",
             "steps": [("scroll", 600), ("pause", 1.4)]},
            {"chapter": "Compliance & filing",
             "narration": "The compliance page tracks your statutory obligations: monthly P A Y E returns to the N R A and NASSIT contribution schedules. SaloneHCM generates the exports in the exact expected format — pick the period, generate, and file. Deadlines are tracked so nothing slips.",
             "steps": [("goto", "/compliance"), ("scroll", 350), ("pause", 1.0)]},
            {"chapter": "Wrap-up",
             "narration": "The golden rules: preview before you run, never bypass a blocked budget check, and file returns before the deadline. Take the payroll officer quiz in the Training Center to certify your skills.",
             "steps": [("slide", "Payroll Officer Training complete", "Take the Payroll quiz", "Preview first. Respect budget checks. File on time.")]},
        ],
    },
    # ------------------------------------------------------------------
    {
        "slug": "vouchers-deep-dive",
        "title": "Payroll Vouchers Deep-dive — branch submission to MoF authorization",
        "summary": "The centralized voucher repository end-to-end: branch submission, supervisor approval, finance review, MoF payment authorization — and the anti-fraud rails at every step.",
        "persona": "government", "sort": 50,
        "scenes": [
            {"chapter": "Welcome",
             "narration": "Welcome to the payroll voucher deep-dive. Before SaloneHCM, branches emailed spreadsheets or carried paper vouchers to headquarters. Now, every branch submits into one central digital repository, and every voucher passes a strict approval chain before a single leone moves. Let's walk the full journey.",
             "steps": [("slide", "Module 5 · Deep-dive", "Payroll Vouchers", "One central repository · branch → supervisor → finance → MoF · immutable audit trail")]},
            {"chapter": "The central repository",
             "narration": "This is the central repository. The indicator cards show how many branches have submitted this period, what's awaiting supervisor sign-off, what's in finance review, and what's been authorised for payment. Filters let you slice by period, branch, and workflow stage.",
             "steps": [("login", *ADMIN), ("goto", "/vouchers"), ("pause", 1.2), ("scroll", 200)]},
            {"chapter": "Inside a voucher",
             "narration": "Open any voucher and you see the full story: every employee line with gross pay, P A Y E, NASSIT, loan deductions and net pay; the totals; and the complete audit timeline — who created it, who approved it, and exactly when. Once submitted, a voucher is frozen. Nobody can quietly change a number.",
             "steps": [("click", '[data-testid^="voucher-row-"]'), ("pause", 1.6), ("scroll", 350), ("pause", 1.2), ("press", "Escape")]},
            {"chapter": "The approval chain",
             "narration": "The workflow enforces four eyes at minimum. A branch officer submits. The branch supervisor approves. A finance officer reviews and approves — and the system physically blocks anyone from approving a voucher they created themselves. Finally a Ministry of Finance approver authorises payment — and that person must be different from both the creator and the finance approver. Dual control, enforced by software, not by trust.",
             "steps": [("scroll", 250), ("pause", 2.0)]},
            {"chapter": "Returns & corrections",
             "narration": "Mistakes happen. Instead of editing in place, a reviewer returns the voucher with a written reason — at least ten characters, always recorded. The branch corrects the figures, resubmits, and the revision number increments. The correction history is permanent.",
             "steps": [("pause", 1.5)]},
            {"chapter": "Fraud rails",
             "narration": "And the quiet protections: one voucher per branch per period — duplicates are rejected. An employee cannot appear on two vouchers in the same month — that's the double-pay guard. And once payment is authorised, the voucher becomes a permanent immutable record. This is how payroll fraud loopholes get closed.",
             "steps": [("scroll", -250), ("pause", 1.6)]},
            {"chapter": "Wrap-up",
             "narration": "Submit digitally, approve in chain, return with reasons, and let the rails do their work. The voucher certification quiz awaits you in the Training Center.",
             "steps": [("slide", "Voucher Deep-dive complete", "Take the Vouchers quiz", "Four-eyes approval · double-pay guards · immutable records")]},
        ],
    },
    # ------------------------------------------------------------------
    {
        "slug": "employee-self-service",
        "title": "Employee Self-Service — payslips, leave & attendance",
        "summary": "For every employee: view and download payslips, request leave, clock attendance, and keep your personal records current — all from your own portal.",
        "persona": "general", "sort": 60,
        "scenes": [
            {"chapter": "Welcome",
             "narration": "Welcome to SaloneHCM employee self-service training. This short session shows you everything you can do yourself — see your payslips, request leave, record attendance, and check your details — without waiting in line at the H R office.",
             "steps": [("slide", "Module 6 · Employees", "Employee Self-Service", "Your payslips · leave requests · attendance · personal records")]},
            {"chapter": "Signing in",
             "narration": "Sign in with the work email and password H R gave you. If you forget your password, your administrator can reset it in seconds. Let's sign in as Joseph, a civil servant.",
             "steps": [("login", *EMP)]},
            {"chapter": "Your payslips",
             "narration": "The self-service page is your home. Your payslips are listed with gross pay, deductions, and net pay for every month. Open any one to see the full breakdown — your P A Y E tax, your NASSIT contribution, any loan repayment — and download the P D F for your records or a bank loan application.",
             "steps": [("goto", "/self-service"), ("pause", 1.0), ("scroll", 400), ("pause", 1.0)]},
            {"chapter": "Requesting leave",
             "narration": "Need time off? Go to leave, press new request, choose your dates and leave type, and submit. Your manager is notified immediately, and you can watch the status change from pending to approved right here. Your remaining balance always shows, so there's never a guessing game.",
             "steps": [("goto", "/leave"), ("hover", '[data-testid="leave-new-button"]'), ("pause", 1.2), ("scroll", 250)]},
            {"chapter": "Attendance",
             "narration": "On the attendance page you clock in and out, and review your own history. If something looks wrong — a missed clock-out, for example — tell your H R officer and they can correct it, with the correction logged.",
             "steps": [("goto", "/attendance"), ("scroll", 300)]},
            {"chapter": "Wrap-up",
             "narration": "That's it — payslips, leave, and attendance, all in your own hands. If you're unsure about anything, the Training Center has a quick reference card made just for employees. Thanks for watching.",
             "steps": [("slide", "Self-Service complete", "You're in control", "Payslips, leave and attendance — no queues, no paper.")]},
        ],
    },
    # ------------------------------------------------------------------
    {
        "slug": "gov-modules-tour",
        "title": "Government Modules Tour — civil service, establishment & transparency",
        "summary": "For MDAs and government payroll teams: grade & step salary structure, establishment control, pre-payroll budget checks, and the public transparency portal.",
        "persona": "government", "sort": 70,
        "scenes": [
            {"chapter": "Welcome",
             "narration": "Welcome to the government modules tour. SaloneHCM's Gov tier adds the controls public payroll demands: a civil service salary structure, establishment discipline, budget checks before money moves, and public transparency. Let's tour each one.",
             "steps": [("slide", "Module 7 · Government", "Government Modules Tour", "Civil service structure · establishment control · budget checks · transparency portal")]},
            {"chapter": "Civil service structure",
             "narration": "The civil service module holds your grade and step salary matrix, allowance rules, and budget codes. Salaries flow from the structure — not from ad-hoc numbers — so a grade seven step three officer in Bo earns exactly what the structure says, same as in Freetown. Retro-pay and ghost-worker audit tools live here too.",
             "steps": [("login", *ADMIN), ("goto", "/civil-service"), ("pause", 1.2), ("scroll", 400), ("pause", 1.0)]},
            {"chapter": "Establishment control",
             "narration": "Establishment control compares approved posts against filled posts, ministry by ministry. Over-establishment hiring gets flagged before it becomes a payroll liability, and vacancies are visible for workforce planning.",
             "steps": [("goto", "/establishment"), ("scroll", 350), ("pause", 1.0)]},
            {"chapter": "Budget checks",
             "narration": "Before any payroll run commits, the budget check verifies there's allocation left on every budget code the run will consume. If a code is over, the run is blocked — and only a documented override with a reason can proceed. On the payroll page, the budget balances panel shows exactly where each code stands.",
             "steps": [("goto", "/payroll"), ("click", '[data-testid="toggle-budget-balances"]'), ("pause", 1.6), ("scroll", 300)]},
            {"chapter": "Transparency portal",
             "narration": "Finally, the open-gov transparency portal — a public page, no login required — publishing aggregate payroll statistics for your ministry: headcount, wage bill trends, and grade distributions. Citizens and journalists see the numbers; personal data stays protected.",
             "steps": [("goto", "/transparency/government-of-sierra-leone"), ("pause", 1.4), ("scroll", 500), ("pause", 1.0)]},
            {"chapter": "Wrap-up",
             "narration": "Structure, establishment, budget discipline, and daylight — the four pillars of clean government payroll. Take the government modules quiz in the Training Center to complete your certification.",
             "steps": [("slide", "Government Tour complete", "Take the Gov Modules quiz", "Structure · establishment · budget checks · transparency")]},
        ],
    },
]
